Feat/accept all invites
Buckitup-chat/chat pull request #233
Opened 2023-03-24 11:46 UTC by sviatosluv

2023-03-24 17:53 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/page/dialog.ex
> +    if rooms |> Enum.any?(&(&1.private_key == new_room_identity.private_key)) do
please rewrite using `room_map`

2023-03-27 00:47 UTC, sviatosluv commented
@sergey-lukianov should an invite update be broadcasted to the channel?

2023-03-29 09:58 UTC, sergey-lukianov requested changes

2023-03-29 09:58 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/page/dialog.ex
> +    if Identity.pub_key(new_room_identity) in Map.keys(room_map) do
Map.has_key?

2023-03-29 09:58 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/page/dialog.ex
> +    if Identity.pub_key(new_room_identity) in Map.keys(room_map) do
Map.has_key?

2023-03-31 12:49 UTC, sergey-lukianov approved these changes

2023-03-31 12:49 UTC, merged