hopefully works
Buckitup-chat/chat pull request #295
Opened 2023-04-24 07:33 UTC by illia-kuznietsov

closes #260

2023-04-25 11:56 UTC, sviatosluv commented on lib/chat_web/live/main_live/index.html.heex
> +      </.modal>
You can also represent the entire modal as a LiveComponent. See `open_modal/3`. 
This is not necessary, but just FYI

2023-04-25 12:04 UTC, sviatosluv commented on lib/chat_web/live/main_live/layout/secret_sharing_form.ex
> +     |> assign(:threshold, 3)}
You may use `ok/1` and `noreply/1` helpers in the callback responses.
This is not necessary, but just FYI

2023-04-26 08:13 UTC, sergey-lukianov requested changes

2023-04-26 08:13 UTC, sergey-lukianov commented on CHANGELOG.md
> +- After clicking the button, secret shares will be sent to chosen users via text message
one line per PR, please

2023-04-26 08:13 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/layout/secret_sharing_form.ex
> +    {:ok,
use `ok/1` helper

2023-04-26 08:13 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/layout/secret_sharing_form.ex
> +      |> Enum.sort_by(&elem(&1, 1))
1. This list includes myself, which is wrong
2. `UsersBrocker` is a better source of users

2023-04-26 08:13 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/layout/secret_sharing_form.ex
> +     |> assign(:selected_kind, kind)}
use `noreply` helper please

2023-04-26 08:13 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/layout/secret_sharing_form.ex
> +      Text.new(share |> Base.encode64(), DateTime.utc_now() |> DateTime.to_unix())
bad time source. See user monotonic_offset

2023-04-28 08:43 UTC, closed without merging