AdminDb docs
Buckitup-chat/chat pull request #301
Opened 2023-04-25 22:20 UTC by sviatosluv

2023-04-26 07:54 UTC, sergey-lukianov requested changes

2023-04-26 07:54 UTC, sergey-lukianov commented on CHANGELOG.md
> +- Error entering room on main drive fix
Leaked from another PR ?

2023-04-26 07:54 UTC, sergey-lukianov commented on lib/chat/admin_db_structures.livemd
> +When new USB drive is plugged into the secondary port,the following functionality will be started.
When empty USB drive ....
Functionalities: 
 - backup - full backup of main drive
 - onliners - backup of data in scope of online (at this moment) users
 - cargo - special cargo scenario

2023-04-26 07:54 UTC, sergey-lukianov commented on lib/chat/admin_db_structures.livemd
This should be linked in README.md as well

2023-04-26 09:00 UTC, sviatosluv commented on lib/chat/admin_db_structures.livemd
already done

2023-04-27 12:12 UTC, sergey-lukianov approved these changes

2023-04-27 12:12 UTC, merged