Social sharing. Filter out bad parts
Buckitup-chat/chat pull request #342
Opened 2023-05-12 11:25 UTC by roman-khomenko-dev

Check for a bad social_part data and highlight them in UI

2023-05-12 13:43 UTC, sergey-lukianov requested changes

2023-05-12 13:43 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/page/recover_key_share.ex
> +        disabled={!@changeset.valid? || Enum.any?(@shares, &KeyShare.broken?(&1))}
`&fun/1 ` syntax is better here

2023-05-12 13:43 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/page/recover_key_share.ex
> +      if(Enum.any?(shares, &KeyShare.broken?(&1)),
same

2023-05-12 13:43 UTC, sergey-lukianov commented on CHANGELOG.md
> +- Social sharing. filter out bad parts
update `main` brach and move this line in unreleased section

2023-05-15 13:42 UTC, sergey-lukianov requested changes

2023-05-15 15:57 UTC, roman-khomenko-dev commented on lib/chat/key_share.ex
> +      [:error | _] -> :error
changed to use `content_result/1` where check for any element is :error

2023-05-15 16:16 UTC, sergey-lukianov approved these changes

2023-05-15 16:22 UTC, merged