Messages download
Buckitup-chat/chat pull request #61
Opened 2022-12-06 18:32 UTC by almirsarajcic

@sergey-lukianov, can you please check if I'm heading in the right direction?

~~When the user selects messages we go through the files, create an archive in the memory, and put the files inside.
Then we redirect the user to the file URL.~~

https://user-images.githubusercontent.com/845364/205993057-73b3ec29-3001-4351-b20f-36b8f0e81109.mov

~~While working on this I've found two ways of letting the user download it:~~
1. ~~create the chunk, save the file in the DB, and redirect the user to the file URL~~
2. ~~save the archive in the static directory and redirect the user to the static path~~

~~If we proceed with saving an archive in the DB, we'll need to create multiple chunks as currently there's an issue if the archive is larger than 10 MB (see the comments).~~

TODO:
- [x] Enable download in Chat (Dialog)
- [x] Enable download in Room

2022-12-07 08:37 UTC, sergey-lukianov commented
@almirsarajcic  The feature ideal outcome is zip archive with 
- `index.html` - decrypted selected messages rendered as in chat (linked to `files/`)
- `files/` dir to hold decrypted file attachments

Tech design
- frontend passes ids of messages to render
- LiveView saves decryption key, message ids and dialog key in `Broker`
- User is redirected to ZipController having broker_key as url param
- ZipController reads out dialog messages and files. Generates streamed zip archive (with something like Zstream)

We never store decrypted content

Zstream - https://hexdocs.pm/zstream/readme.html

2022-12-08 19:19 UTC, almirsarajcic commented
Thanks, @sergey-lukianov! 👍

Here's the new approach:
https://user-images.githubusercontent.com/845364/206547469-37c6d462-88d3-4b56-8c15-13119ee37cf2.mov

It currently only works for the dialog, but tomorrow I'll enable it in the rooms as well, and add the finishing touches.

2022-12-09 08:55 UTC, sergey-lukianov commented on lib/chat_web/controllers/zip_controller.ex
> +            entry = Zstream.entry("files/#{filename}", file_stream)
`filename` comes from user and may conflict when put a bunch of them in a dir.
Maybe add suffix to filename

2022-12-09 08:55 UTC, sergey-lukianov commented on lib/chat_web/controllers/zip_controller.ex
> +               file_stream <- ChunkedFiles.stream_chunks(chunk_key, chunk_secret) do
`file_stream` is a binary with whole file, not a stream. This needs to be stream to make memory footprint not to reflect file size. Files could be huge. Target system may have 2G of physical RAM only

2022-12-09 08:55 UTC, sergey-lukianov commented on lib/chat_web/controllers/zip_controller.ex
> +        |> put_resp_header("content-disposition", "attachment; filename=messages.zip")
Neat: may be introduce some naming pattern so user will know what is in it

2022-12-09 08:55 UTC, sergey-lukianov commented on lib/chat_web/controllers/zip_controller.ex
> +               file_stream <- ChunkedFiles.stream_chunks(chunk_key, chunk_secret) do
File chunk go back to db. So there would be `CubDB.Select` to get a scream of chunks.
Check the https://github.com/Buckitup-chat/chat/pull/63 or wait till it gets into master. Btw, any critics is appreciative

2022-12-09 08:58 UTC, sergey-lukianov commented
Overall looks great.
I do not see a clear reason to make `ExportedMessage` out of `Message`. Lets finish current functionality and then discuss

2022-12-09 19:30 UTC, almirsarajcic commented
The reason why I've extracted the `ExportedMessage` component is that these messages have a header without the options, but also the files are shown differently.

I've reduced the amount of code in it, though, as I'm now relying on the original `Message` component for rendering other types of messages that don't contain files.

2022-12-12 18:07 UTC, sergey-lukianov requested changes

2022-12-12 18:07 UTC, sergey-lukianov commented on lib/chat_web/controllers/zip_controller.ex
> +            filename = Enum.join(filename, ".") <> "_" <> id <> "." <> extension
Reuse this in message render as well

2022-12-12 18:07 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/layout/exported_message.ex
> +    filename = Enum.join(filename, ".") <> "_" <> id <> "." <> extension
copy-paste detected

2022-12-12 18:07 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/page/room.ex
> +    push_event(socket, "chat:redirect", %{url: Routes.zip_url(socket, :get, key)})
verified routes here too, please

2022-12-12 18:12 UTC, sergey-lukianov commented on lib/chat_web/live/main_live/layout/exported_message.ex
> +  def message_block(assigns) do
I see that text messages are reused
May we do so for files as well ?

2022-12-15 09:32 UTC, almirsarajcic commented on lib/chat_web/live/main_live/layout/message.ex
> +          false
I assumed the downloaded messages should look the same regardless of who downloaded them. I'll fix that.

2022-12-16 06:43 UTC, sergey-lukianov approved these changes

2022-12-16 06:43 UTC, merged